env_type: metaworld
task_suite_name: metaworld_45_ind

total_num_envs: null

auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 100
max_episode_steps: 100 # max episode steps for truncation

use_rel_reward: True
reward_coef: 1.0
is_eval: False

seed: 0
group_size: 1
use_fixed_reset_state_ids: False
use_ordered_reset_state_ids: False

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  camera_heights: 480
  camera_widths: 480
